project:
  type: book

book:
  title: "El Arquitecto Invisible"
  author: "Filus & Aisa"
  date: today
  favicon: img/favicon.png
  repo-url: https://github.com/tu-usuario/tu-repo
  repo-branch: main
  repo-actions: [edit, issue]
  sharing: [linkedin]
  open-graph: true
  image: img/cover_page_scriberia.png
  downloads: [pdf, epub]
  chapters:
    - index.qmd
    - cap.qmd
    - tu.qmd
    - filus.qmd

format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, css/theme-dark.scss]
    include-in-header: html/header.html
    description-meta: "This guide is a comprehensive resource for contributors (from all levels, beginners, intermediate, and seasoned) to the R project, facilitating their onboarding and helping them navigate the contribution process."
  pdf:
    documentclass: scrbook
    pdf-engine: lualatex
    include-in-header: 
     - tex/preamble.tex
     - tex/fonts.tex
    include-before-body: tex/frontpage.tex
    keep-tex: true
    toc: true
    number-sections: true
  epub:
    cover-image: img/cover_page.png