project:
  type: book

book:
  title: "Tu Libro"
  author: "Tu Nombre"
  date: today
  favicon: img/favicon.png
  repo-url: https://github.com/tu-usuario/tu-repo
  repo-branch: main
  chapters:
    - index.qmd
    #- cap.qmd
    #- tu.qmd

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrbook
    pdf-engine: lualatex
    include-in-header: 
     - tex/preamble.tex
     - tex/fonts.tex
    include-before-body: tex/frontpage.tex
    keep-tex: true
    toc: true
    number-sections: true
  epub:
    cover-image: img/cover_page.png